### ISSUE TITLE
README - Create a List of Skills Added

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/Alexa-skills-starters#1]
Requirement is to enlist all these Skills as a List in the README. 📜
The List should mention the Name of the Creator, the Skill name - clickable link.
The List should update each time, a new skill's PR is created.

Please let us know about your approach before asking to be assigned.

**Comment by fomalhauting** [comment]
I am a participant of SWoC, and I would like to work on this throughout the period of SWoC.

**Comment by fomalhauting** [comment]
@garimasingh128 Should I add the skills after they are merged?

**Comment by garimasingh128** [comment]
Yes. We can keep it on hold till atleast 2-3 PRs are not merged.

**Comment by garimasingh128** [comment]
Yes. We can keep it on hold till atleast 2-3 PRs are not merged.

**Comment by garimasingh128** [comment]
Also you need to create a script or a GitHub action that creates a pr to add in the readme everytime a skill pr is merged. We don't have to add it manually everytime.
