### ISSUE TITLE
Add readme's for newly added Skills

### ISSUE THREAD

**Issue by dalalvarun** [garimasingh128/Alexa-skills-starters#28]
The newly added skills don't contain proper Readme files.

**Comment by dalalvarun** [comment]
Assign this to me

**Comment by garimasingh128** [comment]
Please elaborate which skills.

**Comment by dalalvarun** [comment]
Alexa-Get-Quote
(It has a markdown file but it isn't  named as README.md and so it doesn't show up automatically when we open that folder)

**Comment by garimasingh128** [comment]
I think that's not much of an issue of MD file names for the individual skills. Let it be.
